# Generated by Django 3.2.12 on 2023-02-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form_15', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form15',
            name='Day',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
