# Generated by Django 3.2.12 on 2023-02-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form1',
        ),
    ]
