# Generated by Django 3.2.12 on 2023-02-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Form_1', '0002_delete_form1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(blank=True, max_length=512)),
                ('B', models.CharField(blank=True, max_length=512)),
                ('type', models.CharField(blank=True, max_length=512)),
                ('C', models.CharField(blank=True, max_length=512)),
                ('D', models.CharField(blank=True, max_length=512)),
                ('Registerd_in_Class', models.CharField(blank=True, max_length=512)),
                ('Under_No', models.CharField(blank=True, max_length=512)),
                ('E1', models.CharField(blank=True, max_length=512)),
                ('E2', models.CharField(blank=True, max_length=512)),
                ('E3', models.CharField(blank=True, max_length=512)),
                ('E4', models.CharField(blank=True, max_length=512)),
                ('F', models.CharField(blank=True, max_length=512)),
                ('Email', models.CharField(blank=True, max_length=512)),
                ('Mobile', models.CharField(blank=True, max_length=512)),
                ('Declaration', models.CharField(blank=True, max_length=512)),
                ('Day', models.CharField(blank=True, max_length=2)),
                ('Month', models.CharField(blank=True, max_length=2)),
                ('Year', models.CharField(blank=True, max_length=2)),
                ('Sign', models.ImageField(blank=True, upload_to='Sign/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
